version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - npm install
  build:
    commands:
      - $(npm bin)/ng build --prod --vendor-chunk --common-chunk --extract-css
  post_build:
    commands:
      - npm run post:build
      - aws s3 sync ./dist s3://${S3_BUCKET} --delete
      # - aws s3 sync ./dist s3://${S3_BUCKET} --acl 'public-read' --delete
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths '/*'
